name: Apply at most one `t-`label to PRs

on: pull_request

jobs:
  apply_one_t_label:
    runs-on: ubuntu-latest
    # Don't run on forks, where we wouldn't have permissions to add the label anyway.
    if: github.repository == 'leanprover-community/mathlib4'
    permissions:
      issues: write
      checks: write
      pull-requests: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v3.1.1/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> "${GITHUB_PATH}"

      - run: |
          git checkout master
          lake exe cache get
          git checkout -
          ./scripts/autolabels.sh long
          printf 'About to add the following labels: "%s"\n' "$(./scripts/autolabels.sh)"
          LABELS="$(./scripts/autolabels.sh)"
          printf $'gh issue edit \'%s\' --add-label \'%s\'\n' "$NUMBER" "$LABELS"
          if [ -z "$LABELS" ]
          then
            printf 'No labels found\n'
          elif [[ $LABELS != *,* ]]
          then
            printf 'Actually doing it!\n'
            sed -i 's=  --\(IO.Process.run gh\)=  \1=' Mathlib/labels.lean
            printf '* File after sed:\n%s\n\n' "$(cat Mathlib/labels.lean)"
            #gh issue edit "$NUMBER" --add-label "$LABELS"
            lake build Mathlib.labels
          else
            printf 'More than one label found: not adding a label\n'
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.number }}
