name: Calendar event reminder

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes
  push:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip requests icalendar

    - name: checkout repo to get leanCal script
    - uses: actions/checkout@v4

    - name: Collect calendar reminders
      id: collect_msg
      run: |
        printf $'summary<<EOF\n%s\nEOF' "$(python scripts/leanCal.py ${{ secrets.MAINTAINER_CALENDAR_URL }})" >> "$GITHUB_OUTPUT"

    - name: Post output to Zulip
      uses: zulip/github-actions-zulip/send-message@v1
      if: "${{contains(steps.collect_msg.outputs.summary, 'eminder')}}"
      with:
        api-key: ${{ secrets.ZULIP_API_KEY }}
        email: 'github-mathlib4-bot@leanprover.zulipchat.com'
        organization-url: 'https://leanprover.zulipchat.com'
        to: 'mathlib maintainers'
        type: 'stream'
        topic: 'Event reminders'
        content: ${{ steps.collect_msg.outputs.summary }}
