name: Find labels

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      #with:
      #  fetch-depth: 0

    - name: Get labels
      run: |
          labels="$(gh api --jq '.labels.[].name' /repos/{owner}/{repo}/pulls/${{ github.event.number }})"
          printf 'Labels:\n---\n%s\n---\n' "${labels}"
          topic="generic"
          tlabels="$(printf '%s' "${labels}" | grep "^t-")"
          printf 't-labels:\n---\n%s\n---\n' "${tlabels}"
          #t_label=""
          #count=0
          #while read -r label; do
          #  printf $'inspecting "%s"\n' "${label}"
          #  if [[ "$label" == t-* ]]; then
          #    t_label="$label"
          #    count=$((count + 1))
          #  fi
          #done < <(jq -r '.[].name' <<< "${{ github.event.pull_request.labels }}")
          #if [[ "$count" -eq 1 ]]; then
          #  topic="$t_label"
          #fi
          #echo "name=topic::maintainer merge: ${topic}" #>> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
