name: Find labels

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      #with:
      #  fetch-depth: 0

    - name: Get labels
      run: |
          tlabels="$(gh api --jq '.labels.[].name' "${PR}" | grep -- '^t-' || printf 'generic')"
          printf 't-labels:\n---\n%s\n---\n' "${tlabels}"
          if [[ "$(wc -l <<<"${tlabels}")" -ne 1 ]]; then
            tlabels="generic"
          fi
          printf 'echo "name=topic::maintainer merge: %s"\n' "${tlabels}"
          echo "name=topic::maintainer merge: ${tlabels}" >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR: /repos/{owner}/{repo}/pulls/${{ github.event.number }}
