name: Find labels

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      #with:
      #  fetch-depth: 0

    - name: Get labels
      run: |
          echo "${{ github.event.pull_request.labels }}"
          jq -r '.[].name' <<< "${{ github.event.pull_request.labels }}"
          topic="generic"
          t_label=""
          count=0
          while read -r label; do
            printf $'inspecting "%s"\n' "${label}"
            if [[ "$label" == t-* ]]; then
              t_label="$label"
              count=$((count + 1))
            fi
          done < <(jq -r '.[].name' <<< "${{ github.event.pull_request.labels }}")
          if [[ "$count" -eq 1 ]]; then
            topic="$t_label"
          fi
          echo "name=topic::maintainer merge: ${topic}" #>> "$GITHUB_OUTPUT"
