# https://chat.openai.com/share/26102e95-ac9c-4d03-a000-73e4f6cee8cd
name: lean4checker Workflow

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day

jobs:
  check-lean4checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: 'master'

      - name: Check environments using lean4checker
        id: lean4checker
        run: |
          git clone https://github.com/leanprover/lean4checker
          cd lean4checker
          git checkout toolchain/v4.7.0
          # Now that the git hash is embedded in each olean,
          # we need to compile lean4checker on the same toolchain
          cp ../lean-toolchain .
          lake build
          ./test.sh
          cd ..
          lake env lean4checker/.lake/build/bin/lean4checker

      - name: Post success message on Zulip
        if: success()
        uses: zulip/github-actions-zulip/send-message@v1
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: 'github-mathlib4-bot@leanprover.zulipchat.com'
          organization-url: 'https://leanprover.zulipchat.com'
          to: 'mathlib reviewers'
          type: 'stream'
          topic: 'lean4checker'
          content: |
            ✅ lean4checker succeeded on ${{ github.sha }}

      - name: Post failure message on Zulip
        if: failure()
        uses: zulip/github-actions-zulip/send-message@v1
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: 'github-mathlib4-bot@leanprover.zulipchat.com'
          organization-url: 'https://leanprover.zulipchat.com'
          to: 'mathlib reviewers'
          type: 'stream'
          topic: 'lean4checker failure'
          content: |
            ❌ lean4checker failed on ${{ github.sha }}
        continue-on-error: true

      - name: Post failure message on Zulip main topic
        if: failure()
        uses: zulip/github-actions-zulip/send-message@v1
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: 'github-mathlib4-bot@leanprover.zulipchat.com'
          organization-url: 'https://leanprover.zulipchat.com'
          to: 'mathlib reviewers'
          type: 'stream'
          topic: 'lean4checker'
          content: |
            ❌ lean4checker failed on ${{ github.sha }}
        continue-on-error: true
