# https://chat.openai.com/share/26102e95-ac9c-4d03-a000-73e4f6cee8cd
name: lean4checker Workflow

on: push
#  schedule:
#    - cron: '0 0 * * *' # Runs at 00:00 UTC every day

#build:
#  if: github.repository MAIN_OR_FORK 'leanprover-community/mathlib4'
#  name: BuildJOB_NAME


jobs:
  check-lean4checker:
    runs-on: ubuntu-latest
    steps:

#old

      - name: cleanup
        run: |
          find . -name . -o -prune -exec rm -rf -- {} +
          # Delete all but the 5 most recent toolchains.
          # Make sure to delete both the `~/.elan/toolchains/X` directory and the `~/.elan/update-hashes/X` file.
          # Skip symbolic links (`-type d`), the current directory (`! -name .`), and `nightly` and `stable`.
          if cd ~/.elan/toolchains && find . -maxdepth 1 -type d ! -name . -print0 | xargs -0 ls -1td | grep -v 'nightly$' | grep -v 'stable$' | tail -n +6 | xargs -I {} sh -c 'echo {} && rm -rf "{}" && rm "../update-hashes/{}"'; then
              : # Do nothing on success
          else
              : # Do nothing on failure, but suppress errors
          fi

      # The Hoskinson runners may not have jq installed, so do that now.
      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v1.0.1

      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v3.0.0/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> "${GITHUB_PATH}"

      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: 'master'

##  new

      - name: If using a lean-pr-release toolchain, uninstall
        run: |
          if [[ $(cat lean-toolchain) =~ ^leanprover/lean4-pr-releases:pr-release-[0-9]+$ ]]; then
            printf 'Uninstalling transient toolchain %s\n' "$(cat lean-toolchain)"
            elan toolchain uninstall "$(cat lean-toolchain)"
          fi

      - name: print lean and lake versions
        run: |
          lean --version
          lake --version

## until here

      - name: Run lake exe cache get
        run: |
          lake exe cache get
          lake build


      - name: Check environments using lean4checker
        id: lean4checker
        run: |
          git clone https://github.com/leanprover/lean4checker
          cd lean4checker
          git checkout toolchain/v4.7.0
          # Now that the git hash is embedded in each olean,
          # we need to compile lean4checker on the same toolchain
          cp ../lean-toolchain .
          lake build
          ./test.sh
          cd ..
          lake env lean4checker/.lake/build/bin/lean4checker

#      - name: Post success message on Zulip
#        if: success()
#        uses: zulip/github-actions-zulip/send-message@v1
#        with:
#          api-key: ${{ secrets.ZULIP_API_KEY }}
#          email: 'github-mathlib4-bot@leanprover.zulipchat.com'
#          organization-url: 'https://leanprover.zulipchat.com'
#          to: 'mathlib reviewers'
#          type: 'stream'
#          topic: 'lean4checker'
#          content: |
#            ✅ lean4checker succeeded on ${{ github.sha }}
#
#      - name: Post failure message on Zulip
#        if: failure()
#        uses: zulip/github-actions-zulip/send-message@v1
#        with:
#          api-key: ${{ secrets.ZULIP_API_KEY }}
#          email: 'github-mathlib4-bot@leanprover.zulipchat.com'
#          organization-url: 'https://leanprover.zulipchat.com'
#          to: 'mathlib reviewers'
#          type: 'stream'
#          topic: 'lean4checker failure'
#          content: |
#            ❌ lean4checker failed on ${{ github.sha }}
#        continue-on-error: true
#
#      - name: Post failure message on Zulip main topic
#        if: failure()
#        uses: zulip/github-actions-zulip/send-message@v1
#        with:
#          api-key: ${{ secrets.ZULIP_API_KEY }}
#          email: 'github-mathlib4-bot@leanprover.zulipchat.com'
#          organization-url: 'https://leanprover.zulipchat.com'
#          to: 'mathlib reviewers'
#          type: 'stream'
#          topic: 'lean4checker'
#          content: |
#            ❌ lean4checker failed on ${{ github.sha }}
#        continue-on-error: true
#
