
on:
  pull_request

name: lint and suggest

jobs:
  style_lint:
    if: github.repository == 'leanprover-community/mathlib4' && github.event.pull_request.draft == false
    name: Lint style
    runs-on: ubuntu-latest
    steps:
      - name: cleanup
        run: |
          find . -name . -o -prune -exec rm -rf -- {} +

      - uses: actions/checkout@v4

      - name: install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: lint
        continue-on-error: true
        run: |
          ./scripts/lint-style.sh --fix

      # This is failing with
      #   reviewdog: fail to get diff: GET https://api.github.com/repos/leanprover-community/mathlib4/pulls/11997: 406
      #   Sorry, the diff exceeded the maximum number of files (300).
      #   Consider using 'List pull requests files' API or locally cloning the repository instead.
      #   [{Resource:PullRequest Field:diff Code:too_large Message:}]
      # - name: suggester / lint-style
      #   uses: reviewdog/action-suggester@v1
      #   with:
      #     tool_name: lint-style

      - name: Install bibtool
        run: |
          sudo apt-get update
          sudo apt-get install -y bibtool

      - name: lint references.bib
        continue-on-error: true
        run: |
          ./scripts/lint-bib.sh

      # This is failing with
      #   reviewdog: fail to get diff: GET https://api.github.com/repos/leanprover-community/mathlib4/pulls/11997: 406
      #   Sorry, the diff exceeded the maximum number of files (300).
      #   Consider using 'List pull requests files' API or locally cloning the repository instead.
      #   [{Resource:PullRequest Field:diff Code:too_large Message:}]
      # - name: suggester / lint-bib
      #   uses: reviewdog/action-suggester@v1
      #   with:
      #     tool_name: lint-bib

  check_imported:
    if: github.repository == 'leanprover-community/mathlib4' && github.event.pull_request.draft == false
    name: Check all files imported
    runs-on: ubuntu-latest
    steps:
      - name: cleanup
        run: |
          find . -name . -o -prune -exec rm -rf -- {} +

      - uses: actions/checkout@v4

      - name: update Mathlib.lean
        run: |
          git ls-files 'Mathlib/*.lean' | LC_ALL=C sort | sed 's/\.lean//;s,/,.,g;s/^/import /' > Mathlib.lean

      - name: update Mathlib/Tactic.lean
        run: |
          git ls-files 'Mathlib/Tactic/*.lean' | LC_ALL=C sort | sed 's/\.lean//;s,/,.,g;s/^/import /' > Mathlib/Tactic.lean

      - name: update Counterexamples.lean
        run: |
          git ls-files 'Counterexamples/*.lean' | LC_ALL=C sort | sed 's/\.lean//;s,/,.,g;s/^/import /' > Counterexamples.lean

      - name: update Archive.lean
        run: |
          git ls-files 'Archive/*.lean' | LC_ALL=C sort | sed 's/\.lean//;s,/,.,g;s/^/import /' > Archive.lean

      # This is failing with
      #   reviewdog: fail to get diff: GET https://api.github.com/repos/leanprover-community/mathlib4/pulls/11997: 406
      #   Sorry, the diff exceeded the maximum number of files (300).
      #   Consider using 'List pull requests files' API or locally cloning the repository instead.
      #   [{Resource:PullRequest Field:diff Code:too_large Message:}]
      # - name: suggester / import list
      #   uses: reviewdog/action-suggester@v1
      #   with:
      #     tool_name: imports
