on:
  pull_request

name: lint and suggest

jobs:
  style_lint:
    if: github.repository == 'leanprover-community/mathlib4' && github.event.pull_request.draft == false
    name: Lint style
    runs-on: ubuntu-latest
    steps:
      - uses: leanprover-community/lint-style-action@f2e7272aad56233a642b08fe974cf09dd664b0c8 # 2025-05-22
        with:
          mode: suggest
          lint-bib-file: true
      - name: All Mathlib files have lean or md extension
        run: |
          exc="$(git ls-files 'Mathlib/*' | grep -v "\.\(lean\|md\)$")"
          if [ -n "${exc}" ];
          then
            printf $'There are files whose extension is neither \'.lean\' nor \'.md\' in Mathlib/:\n\n%s\n' "${exc}"
            printf $'\nPlease, make sure that this is really what you want!\n'
            exit 1
          fi
