name: Maintainer merge

# triggers the action when
on:
  repository_dispatch:
    types: [maintainer-command]

jobs:
  ping_zulip:
    # we set some variables from the dispatched payload
    env:
      AUTHOR: ${{ github.event.client_payload.author }}
      PR_AUTHOR: ${{ github.event.client_payload.pr_author }}
      PR_NUMBER: ${{ github.event.client_payload.pr_number }}
      COMMENT_EVENT: ${{ github.event.client_payload.comment_event }}
      COMMENT_REVIEW: ${{ github.event.client_payload.comment_review }}
      PR_TITLE_ISSUE: ${{ github.event.client_payload.pr_title_issue }}
      PR_TITLE_PR: ${{ github.event.client_payload.pr_title_pr }}
      PR_URL: ${{ github.event.client_payload.pr_url }}
      EVENT_NAME: ${{ github.event.client_payload.event_name }}
    name: Ping maintainers on Zulip
    runs-on: ubuntu-latest
    if: github.repository == 'leanprover-community/mathlib4'
    steps:
      - name: Set merge or delegate outputs from payload
        id: merge_or_delegate
        run: |
          echo "PR author: ${PR_AUTHOR}"

          # Get values from the dispatched payload
          m_or_d="${{ github.event.client_payload.mOrD }}"

          printf $'"maintainer delegate" or "maintainer merge" found? \'%s\'\n' "${m_or_d}"

          printf $'mOrD=%s\n' "${m_or_d}" >> "${GITHUB_OUTPUT}"

      - name: Check whether user is part of mathlib-reviewers team
        if: ${{ ! steps.merge_or_delegate.outputs.mOrD == '' }}
        uses: TheModdingInquisition/actions-team-membership@a69636a92bc927f32c3910baac06bacc949c984c # v1.0
        with:
          organization: 'leanprover-community'
          team: 'mathlib-reviewers' # required. The team to check for
          token: ${{ secrets.MATHLIB_REVIEWERS_TEAM_KEY }} # required. Personal Access Token with the `read:org` permission
          comment: 'You seem to not be authorized' # optional. A comment to post if the user is not part of the team.
                                                   # This feature is only applicable in an issue (or PR) context
          exit: true # optional. If the action should exit if the user is not part of the team. Defaults to true.

      - name: Checkout
        if: ${{ ! steps.merge_or_delegate.outputs.mOrD == '' }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Determine Zulip topic
        if: ${{ ! steps.merge_or_delegate.outputs.mOrD == '' }}
        id: determine_topic
        run: |
          ./scripts/get_tlabel.sh "/repos/leanprover-community/mathlib4/issues/${PR_NUMBER}" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Form the message
        if: ${{ ! steps.merge_or_delegate.outputs.mOrD == '' }}
        id: form_the_message
        run: |
          # for debugging, we print the available variables
          echo "github.event.action: '${{ github.event.client_payload.github_event_action }}'"

          echo ""
          message="$(
            ./scripts/maintainer_merge_message.sh "${AUTHOR}" "${{ steps.merge_or_delegate.outputs.mOrD }}" "${EVENT_NAME}" "${PR_NUMBER}" "${PR_URL}" "${PR_TITLE_ISSUE}${PR_TITLE_PR}" "${COMMENT_EVENT}${COMMENT_REVIEW}" "${PR_AUTHOR}"
          )"
          printf 'title<<EOF\n%s\nEOF' "${message}" | tee "$GITHUB_OUTPUT"

      - name: Send message on Zulip
        if: ${{ ! steps.merge_or_delegate.outputs.mOrD == '' }}
        uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5 # v1.0.2
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: 'github-mathlib4-bot@leanprover.zulipchat.com'
          organization-url: 'https://leanprover.zulipchat.com'
          to: 'mathlib reviewers'
          type: 'stream'
          topic: ${{ steps.determine_topic.outputs.topic }}
          content: ${{ steps.form_the_message.outputs.title }}

      - name: Add comment to PR
        if: ${{ ! steps.merge_or_delegate.outputs.mOrD == '' }}
        uses: GrantBirki/comment@608e41b19bc973020ec0e189ebfdae935d7fe0cc # v2.1.1
        with:
          # Use the PR number from the dispatched payload
          issue-number: ${{ github.event.client_payload.pr_number }}
          body: |
            🚀 Pull request has been placed on the maintainer queue by ${{ github.event.client_payload.author }}.

      - name: Add label to PR
        if: ${{ ! steps.merge_or_delegate.outputs.mOrD == '' }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          # labels added by GITHUB_TOKEN won't trigger the Zulip emoji workflow
          github-token: ${{secrets.TRIAGE_TOKEN}}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const issue_number = ${{ github.event.client_payload.pr_number }};
            await github.rest.issues.addLabels({ owner, repo, issue_number, labels: ['maintainer-merge'] });
