on:
  pull_request

name: Blog report

jobs:

  Monthly_PRs:
    if: github.repository == 'leanprover-community/mathlib4' && github.event.pull_request.draft == false
    name: Blog draft
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}
      BRANCH_NAME: ${{ github.head_ref }}

    steps:
      - name: cleanup
        run: |
          find . -name . -o -prune -exec rm -rf -- {} +

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: blog report
        continue-on-error: true
        run: |
          printf $'Repository: %s\nBranch: %s\n' "${{ github.repository }}" "${BRANCH_NAME}"
          git checkout origin/adomani/yd_find_label scripts/find_labels.sh
          ./scripts/find_labels.sh "${{ github.repository }}"
