name: Try to update the style exceptions files
on:
  pull_request:
    types:
      - labeled
  schedule:
    - cron: "*/5 * * * *"

jobs:
  add-comment:
    if: github.event.label.name == 'test-ci'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:

      # The Hoskinson runners may not have jq installed, so do that now.
      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v1.0.1

      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v3.0.0/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> "$GITHUB_PATH"

      - uses: actions/checkout@v4
      - name: get cache
        run: |
          lake exe cache clean
          lake exe cache get

      - name: build mathlib
        id: build
        uses: liskin/gh-problem-matcher-wrap@v3
        with:
          linters: gcc
          run: |
            bash -o pipefail -c "env LEAN_ABORT_ON_PANIC=1 lake build --wfail -KCI"

      - name: lint mathlib and update style exceptions files
        id: lint
        uses: liskin/gh-problem-matcher-wrap@v3
        with:
          linters: gcc
          run: |
            env LEAN_ABORT_ON_PANIC=1 lake exe runLinter Mathlib
            mv nolints.json scripts/nolints.json
            ./scripts/update-style-exceptions.sh
            git diff
