name: Zulip Emoji Merge Delegate

# triggers the action when
on:
  # the PR receives a comment
  issue_comment:
    types: [created]
  # the PR receives a review
  pull_request_review:
    # whether or not it is accompanied by a comment
    types: [submitted]
  # the PR receives a review comment
  pull_request_review_comment:
    types: [created]
  push:
  #schedule:
  #  - cron: '0 * * * *'  # Runs every hour

jobs:
  zulip-emoji-merge-delegate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout mathlib repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          scripts

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install zulip

    - name: Run Zulip Emoji Merge Delegate Script
      env:
        ZULIP_API_KEY: ${{ secrets.ZULIP_API_KEY }}
        ZULIP_EMAIL: github-mathlib4-bot@leanprover.zulipchat.com
        ZULIP_SITE: https://leanprover.zulipchat.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python scripts/zulip_emoji_merge_delegate.py "$ZULIP_API_KEY" "$ZULIP_EMAIL" "$ZULIP_SITE" "[Merged by Bors] and more" "${{ github.event.issue.number }}${{ github.event.pull_request.number }}" #"$GITHUB_TOKEN"
